# Generated by Django 6.0.7 on 2026-07-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='note',
        ),
    ]
