# Generated by Django 5.2.7 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("classes", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(max_length=5000)),
                ("due_at", models.DateTimeField()),
                ("maximum_score", models.PositiveSmallIntegerField(default=100, editable=False)),
                ("classroom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="classes.class")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("maximum_score", models.PositiveSmallIntegerField()),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="assignments.assignment")),
            ],
            options={"ordering": ("id",)},
        ),
    ]
