# Generated by Django 6.0.7 on 2026-07-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
