# Generated by Django 6.0.7 on 2026-07-26 15:25

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

from accounts.seed_data import build_roster


def create_class_tables_and_seed(apps, schema_editor):
    Class = apps.get_model("classes", "Class")
    Enrollment = apps.get_model("classes", "Enrollment")
    User = apps.get_model("accounts", "User")
    tables = set(schema_editor.connection.introspection.table_names())

    if Class._meta.db_table not in tables:
        schema_editor.create_model(Class)
    if Enrollment._meta.db_table not in tables:
        schema_editor.create_model(Enrollment)

    roster = build_roster()
    teachers = [r for r in roster if r["role"] == "TEACHER"]
    students = [r for r in roster if r["role"] == "STUDENT"]
    teacher_anh = User.objects.get(email=teachers[0]["email"])
    teacher_binh = User.objects.get(email=teachers[1]["email"])
    student_an, student_bao, student_chi, student_dung = (
        User.objects.get(email=students[i]["email"]) for i in range(4)
    )

    now = timezone.now()
    python, _ = Class.objects.get_or_create(
        teacher=teacher_anh,
        name="Python Foundations",
        defaults={"description": "Python basics", "starts_at": now - timedelta(days=1), "ends_at": now + timedelta(days=30)},
    )
    django_class, _ = Class.objects.get_or_create(
        teacher=teacher_binh,
        name="Django Fundamentals",
        defaults={"description": "Django basics", "starts_at": now - timedelta(days=1), "ends_at": now + timedelta(days=30)},
    )
    for classroom, student in (
        (python, student_an),
        (python, student_bao),
        (django_class, student_chi),
        (django_class, student_dung),
    ):
        Enrollment.objects.get_or_create(classroom=classroom, student=student)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_seed_demo_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
                ),
                migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('classroom', 'student'), name='unique_class_enrollment')],
            },
                ),
            ],
        ),
        migrations.RunPython(create_class_tables_and_seed, migrations.RunPython.noop),
    ]
