# Generated by Django 6.0.7 on 2026-08-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_created_at_class_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classresource',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classresource',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='classresource',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='classresource',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classresource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddConstraint(
            model_name='classresource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file_path__gt', ''), ('url', '')), models.Q(('file_path', ''), ('url__gt', '')), _connector='OR'), name='class_resource_link_xor_file'),
        ),
    ]
